repos:
  - repo: https://github.com/psf/black
    rev: 21.6b0
    hooks:
      - id: black
        language_version: python3
        args: [--line-length=100, --target-version=py38]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: end-of-file-fixer
        exclude: ^.bumpversion.cfg
      - id: trailing-whitespace
        exclude: ^.bumpversion.cfg
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.910"
    hooks:
      - id: mypy
        name: Lint app with mypy
        entry: mypy dataset_health_example
        pass_filenames: false
        args: [--ignore-missing-imports]
        additional_dependencies:
          - "types-PyYAML"
  - repo: https://github.com/PyCQA/isort
    rev: "5.9.2"
    hooks:
      - id: isort
        name: Sort import with isort
        args: ["-m3", "-w 100", "--tc"]
        # exclude: ^tests/
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.3.2"
    hooks:
      - id: prettier
        exclude: \.html
  - repo: https://github.com/PyCQA/flake8
    rev: "3.9.2"
    hooks:
      - id: flake8
        exclude: ^tests/
        additional_dependencies: [flake8-docstrings]
        args:
          [
            "--max-line-length=120",
            "--ignore=D205,D102,D104,D401,D400,D107,W503,D103,D100,D101",
          ]
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.26.0
    hooks:
      - id: pyupgrade
